# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='arst', max_length=64),
            preserve_default=False,
        ),
    ]
