# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20161213_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('slug',)},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='slug',
        ),
    ]
