# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20161213_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_needs',
            field=models.CharField(choices=[('has', 'I have...'), ('needs', 'I need...')], default='has', max_length=8),
        ),
    ]
